//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentSpell
    {
        public TalentSpell()
        {
            this.Prerequisites = new HashSet<Prerequisite>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Revised { get; set; }
        public Nullable<int> WhichGod { get; set; }
        public Nullable<int> Tier { get; set; }
        public Nullable<int> Cost { get; set; }
        public int Id { get; set; }
        public Nullable<int> AttributeType { get; set; }
        public Nullable<int> Booksource { get; set; }
    
        public virtual AttributeType AttributeType1 { get; set; }
        public virtual BlackCrusadeGod BlackCrusadeGod { get; set; }
        public virtual ICollection<Prerequisite> Prerequisites { get; set; }
        public virtual Booksource Booksource1 { get; set; }
    }
}
